### ISSUE TITLE
NetworkPolicy Watch setup fails when using k8s NetworkPolicy due to invalid ResourceVersion

### ISSUE THREAD

**Issue by breunigs** [projectcalico/typha#335]
## Expected Behavior
Typha succeeds to setup the network policy watch.

## Current Behavior

It fails with this error:
```
2019-12-09 15:44:33.467 [INFO][8] watchercache.go 259: Failed to create watcher
  ListRoot="/calico/resources/v3/projectcalico.org/networkpolicies"
  error=ResourceVersion is not valid: 346124214 performFullResync=false
```
Newlines inserted for readability. Please see [debug.log](https://github.com/projectcalico/typha/files/3940587/clean-debug.log) for context.

## Steps to Reproduce
1. Setup Calico / Typha with KDD store (k8s 1.13, backed by etcd 3.3)
2. Apply network policy (create namespace `stefan-breunig` or change it first):
```yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: internal-traffic-policy
  namespace: stefan-breunig
spec:
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          bla/fqdn: stefandebug         
  podSelector:
    matchExpressions:
    - key: bla/role
      operator: In
      values:
      - application
      - worker
  policyTypes:
  - Egress
```
3. observe Typha logs

## Context

We observed this issue while bringing up a failed cluster (etcd outage). We were confused why Typha was having this error, even after fixing etcd. Since this happens for unrelated clusters with next to no load as well, we suspect this error is not happening due to the etcd outage or high load.

## Your Environment
* Typha version: 3.7.5
* `calico/typha` container version (if running Typha in a container): `calico/typha:v3.7.5`
* orchestrator: Kubernetes 1.13
* Etcd version (if using etcd datastore driver): etcd 3.3, but using `TYPHA_DATASTORETYPE: kubernetes`
* Operating System and version: ubuntu 18.04 (Linux 4.15.0-50-generic)
